---

- name: Create /etc/rc.conf.d/syslogd
  ansible.builtin.template:
    src: FreeBSD.rc.j2
    dest: "/etc/rc.conf.d/{{ syslogd_service }}"
    mode: "0644"
  notify:
    - Restart syslogd

- name: Enable syslogd
  ansible.builtin.service:
    name: "{{ syslogd_service }}"
    enabled: yes
