---
# tasks file for ansible-role-syslogd

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create syslogd_conf_d_dirs
  ansible.builtin.file:
    state: directory
    mode: "0755"
    path: "{{ item }}"
  with_items: "{{ syslogd_conf_d_dirs }}"

- name: Create syslogd_conf_file
  ansible.builtin.template:
    src: syslog.conf.j2
    dest: "{{ syslogd_conf_file }}"
    mode: "0644"
  notify: Restart syslogd

- name: Assert syslogd_config_flagments
  ansible.builtin.assert:
    that:
      - "'state' in item"
      - item['state'] == 'present' or item['state'] == 'absent'
  with_items: "{{ syslogd_config_flagments }}"

- name: Create syslogd_config_flagments
  ansible.builtin.template:
    src: flagment.conf.j2
    dest: "{{ item['path'] }}"
    mode: "{{ item['mode'] | default('0644') }}"
  with_items: "{{ syslogd_config_flagments }}"
  when:
    - item['state'] == 'present'
  notify: Restart syslogd

- name: Delete syslogd_config_flagments
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ syslogd_config_flagments }}"
  when:
    - item['state'] == 'absent'
  notify: Restart syslogd

- name: Start syslogd
  ansible.builtin.service:
    name: "{{ syslogd_service }}"
    state: started
