---
# tasks file for ansible-role-syslogd

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ syslogd_log_dir }}"
    mode: 0755
    owner: "{{ syslogd_user }}"
    group: "{{ syslogd_group }}"
    state: directory
  notify: Restart syslogd

- name: Create db directory
  file:
    path: "{{ syslogd_db_dir }}"
    mode: 0755
    owner: "{{ syslogd_user }}"
    group: "{{ syslogd_group }}"
    state: directory
  notify: Restart syslogd

- name: Create syslogd.conf
  template:
    src: syslogd.conf.j2
    dest: "{{ syslogd_conf_file }}"
    validate: echo %s
  notify: Restart syslogd

- name: Start syslogd
  service:
    name: "{{ syslogd_service }}"
    enabled: true
    state: started
